import * as THREE from '/workspace/yunshan/node_modules/three/build/three.module.js';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createWorld,getWalkHeight} from '/tmp/yunshan-phase2-root-coherent-02/src/world.ts';
import {PlayerController} from '/tmp/yunshan-phase2-root-coherent-02/src/controller.ts';
import {blocksTransportBarrier} from '/tmp/yunshan-phase2-root-coherent-02/src/transport-geometry.ts';
import {canAccessFloor} from '/tmp/yunshan-phase2-root-coherent-02/src/access.ts';
const file='/workspace/yunshan/artifacts/phase2-player-journey-r7-export/resume-ui-export.json',bytes=await readFile(file),save=JSON.parse(bytes.toString()),world=createWorld(save.worldSeed,'current-v2-r5');
const keyboard=Object.assign(new EventTarget(),{closest:()=>null}),doc=Object.assign(new EventTarget(),{pointerLockElement:null});Object.defineProperty(globalThis,'window',{value:keyboard,configurable:true});Object.defineProperty(globalThis,'document',{value:doc,configurable:true});
const target={x:-380.40000000000003,y:45.400000000000006,z:520},body={...save.state.player.position};const controller=new PlayerController(new THREE.PerspectiveCamera(),new EventTarget() as HTMLCanvasElement,world,()=>{},(b,f)=>canAccessFloor(b,f,save.state.player),()=>save.state.voxels??[]);
controller.setMode('walk',body);const initial={body:controller.position,inside:controller.inside?.id??null,floor:controller.floor};const down=new Event('keydown');Object.assign(down,{code:'KeyW',repeat:false});keyboard.dispatchEvent(down);
const trace=[];let blocked=0;
for(let i=0;i<400;i++) {const before=controller.position;controller.yaw=Math.atan2(-(target.x-before.x),-(target.z-before.z));const dx=-Math.sin(controller.yaw)*4.8/60,dz=-Math.cos(controller.yaw)*4.8/60;const cx={x:before.x+dx,y:before.y,z:before.z},cz={x:before.x,y:before.y,z:before.z+dz};const xHeight=getWalkHeight(world,cx.x,cx.z,before.y),zHeight=getWalkHeight(world,cz.x,cz.z,before.y);const checks={xBarrier:blocksTransportBarrier(world,before,cx,.35),zBarrier:blocksTransportBarrier(world,before,cz,.35),xHeight,zHeight,xCliff:Math.abs(xHeight-before.y)>2.6,zCliff:Math.abs(zHeight-before.y)>2.6};controller.step(1/60,false);const after=controller.position;trace.push({step:i,before,cx,cz,checks,after});if(Math.hypot(after.x-before.x,after.z-before.z)<1e-6)blocked++;else blocked=0;if(blocked>=12)break;}
const end=controller.position,last=trace.at(-1);const result={scope:'CPU miniDOM real PlayerController keyboard input against immutable authority, initial raw body from unedited real native UI export. Intentional heading toward the actual failed waypoint; no browser/profile writes, not new GL/player progress.',snapshot:'/tmp/yunshan-phase2-root-coherent-02',exportFile:file,exportSHA256:createHash('sha256').update(bytes).digest('hex'),worldFingerprint:save.worldFingerprint,rawSavedBody:body,initial,target,end,trace,last,fullStationary:blocked>=12};await writeFile('/workspace/yunshan/artifacts/phase2-player-journey-r7/controller-prefix-proof.json',JSON.stringify(result,null,2));console.log(JSON.stringify({body,initial,target,end,last,steps:trace.length,fullStationary:result.fullStationary}));controller.dispose();
