import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {Simulation} from './assembly/src/simulation.ts';
import {createProductCity} from './assembly/src/product-city.ts';
import {coherentPublicEmploymentWorld} from './assembly/tests/public-employment-fixture.ts';
import {getFloorPlanStairPosition,getFloorPlanStairRoute} from './assembly/src/architecture-floor-plan.ts';
import {partitionSave,assembleSave} from './assembly/src/persistence/partition.ts';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex'),world=coherentPublicEmploymentWorld(),sim=createProductCity(world),r=Reflect.get(sim,'runtime'),m=Reflect.get(sim,'npcStairMotion'),site=world.buildings.find(b=>b.kind==='hall')!,actor=sim.state.citizens.find(c=>c.workId===site.id)!;
assert(actor); actor.position=getFloorPlanStairPosition(site,0);actor.route=getFloorPlanStairRoute(site,0,1)!;actor.routeIndex=1;actor.destinationId=site.id;actor.state='moving';
const money=actor.money,needs={...actor.needs};let count=0;
while(true){Reflect.get(sim,'moveCitizen').call(sim,actor,.01);const cursor=r.npcStairCursors[actor.id],d=m.describe(actor.route,actor.routeIndex);if(cursor&&d.kind==='physical'&&d.leg.parts[cursor.piece]?.kind==='riser'&&cursor.offset>0)break;assert(++count<1000);}
assert.equal(actor.money,money);assert.deepEqual(actor.needs,needs);const raw=sim.exportSave(),base=JSON.parse(raw);assert.equal(base.version,3);assert.equal(base.motionVersion,2);assert.equal(base.rulesetId,'civic-local-v1');
function loaded(s:string){const reader=new Simulation(world),result=reader.importSave(s);assert.equal(result.ok,true,result.message);assert.equal(reader.exportSave(),s);return reader;}
const reader=loaded(raw),before=reader.exportSave();assert.equal(assembleSave(partitionSave(raw,world)),raw);
const edits:Record<string,(d:any)=>void>={deleted:d=>delete d.runtime.npcStairCursors[actor.id],mapDeleted:d=>delete d.runtime.npcStairCursors,versionDeleted:d=>delete d.runtime.npcMotionVersion,wrongNativeVersion:d=>d.runtime.npcMotionVersion=3,wrongEnvelope:d=>d.version=1,unknownActor:d=>d.runtime.npcStairCursors.ghost=d.runtime.npcStairCursors[actor.id],unknownKey:d=>d.runtime.npcStairCursors[actor.id].credit=2,wrongCursorVersion:d=>d.runtime.npcStairCursors[actor.id].version=2,NaN:d=>d.runtime.npcStairCursors[actor.id].offset=NaN,negative:d=>d.runtime.npcStairCursors[actor.id].offset=-1,pieceOverflow:d=>d.runtime.npcStairCursors[actor.id].piece=999,routeMismatch:d=>d.runtime.npcStairCursors[actor.id].to.z+=.01,bodyMismatch:d=>d.state.citizens.find((c:any)=>c.id===actor.id).position.y+=.001,bodyString:d=>d.state.citizens.find((c:any)=>c.id===actor.id).position.y=String(actor.position.y),indexMismatch:d=>d.runtime.npcStairCursors[actor.id].routeIndex++};
const bad=[];for(const [label,edit] of Object.entries(edits)){const d=structuredClone(base);edit(d);const text=JSON.stringify(d),result=reader.importSave(text);assert.equal(result.ok,false,label);assert.equal(reader.exportSave(),before,label+' atomic');bad.push({label,sha256:hash(text),result});}
const chunks=loaded(assembleSave(partitionSave(raw,world))),rows=[];
for(let n=1;n<=24;n++){for(const city of [sim,reader,chunks])city.step(.25);const expected=sim.exportSave();assert.equal(reader.exportSave(),expected);assert.equal(chunks.exportSave(),expected);assert.equal(assembleSave(partitionSave(expected,world)),expected);loaded(expected);assert.equal(sim.state.tick,n);assert.equal(sim.state.extension!.lastUpdate,480+n*.25);assert(sim.state.citizens.every(c=>(c.route?.length??0)<=1024));rows.push({n,tick:sim.state.tick,clock:sim.state.extension!.lastUpdate,sha256:hash(expected)});}
writeFileSync(new URL('./native-v3-mid-riser13.save.json',import.meta.url),raw);const result={status:'PASS',scope:'declared coherent native small-city actor supported stair start; actual production mover creates riser cursor; no fabricated canonical wages or time; full/partition/reopen24 actual .25 ticks',actorId:actor.id,controlledPremise:{siteId:site.id,floor:0,routeIntent:'existing canonical stair0->1'},openingSHA256:hash(raw),bad,rows};writeFileSync(new URL('./native-v3-motion13-result.json',import.meta.url),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));
