import assert from 'node:assert/strict';
import test from 'node:test';
import { collectActorActivityClaims, validateJointActorActivityCapacity } from '../src/simulation/activity-capacity.ts';
import type { RoadLaborReceipt, RoadRepairJob } from '../src/simulation/roadworks.ts';
import type { SimState } from '../src/types.ts';

const T = 100, NOW = T + 32;
/** Pure capacity-contract fixtures. These declared receipts have not been
 * generated by Simulation payroll, material purchase or a real repair. The
 * roadworks validator separately authenticates their source and aggregate
 * money/contributions; this test exercises their joint occupied-time bounds. */
function job(id: string, ranges: readonly (readonly [number,number])[], actorId = 'worker'): RoadRepairJob {
  const rate = .2, taxRate = .1, point = {x:0,y:0,z:0};
  const laborReceipts: RoadLaborReceipt[] = ranges.map(([startAt,endAt],index) => {
    const minutes = endAt-startAt, gross = minutes*rate, tax = gross*taxRate;
    return {at:endAt,firstTick:index+1,lastTick:index+1,paymentCount:1,actorId,startAt,endAt,minutes,
      ratePerMinute:rate,taxRate,gross,net:gross-tax,tax,nodeId:'safe',point:{...point}};
  });
  const workedMinutes = laborReceipts.reduce((sum,r)=>sum+r.minutes,0), paidGross = workedMinutes*rate, paidTax = paidGross*taxRate;
  return {id,closureId:'closure-'+id,edgeId:'edge-'+id,requestedBy:'player',payerId:'player',worksiteNodeId:'safe',worksite:point,
    startedAt:T,lastObservedAt:NOW,status:'working',reason:'',workerId:actorId,acceptedAt:T,ratePerMinute:rate,
    contract:{actorId,at:T,role:'工人',craft:20,age:30,health:70,hunger:70,fatigue:70,districtId:'town',prosperity:50,ratePerMinute:rate},
    supplierShopId:'supplier',supplierNodeId:'supply',supplierPoint:{...point},requiredMinutes:60,workedMinutes,
    contributions:ranges.length?{[actorId]:{startedAt:ranges[0][0],endedAt:ranges.at(-1)![1],workedMinutes,gross:paidGross,net:paidGross-paidTax,tax:paidTax}}:{},
    laborReceipts,funded:100,escrow:100-4-paidGross,purchasePaid:4,paidGross,paidNet:paidGross-paidTax,paidTax,refunded:0,serviceFees:0,
    receipts:[{at:T,shopId:'supplier',workerId:actorId,nodeId:'supply',point:{...point},quantity:1,unitPrice:4,gross:4,net:3.6,tax:.4,taxRate:.1}],
    receivedUnits:1,reservedUnits:1,consumedUnits:0,budgetId:null,approvalSiteId:null,approvedAt:null,approvedBy:[],authorizedCap:0,completedAt:null,cancelledAt:null};
}
function state(jobs: RoadRepairJob[]): SimState {
  return {version:1,seed:1,tick:32,day:0,hour:NOW/60,paused:false,speed:1,weather:'晴',visibility:1,energy:80,treasury:1000,taxRate:.1,policeBudget:.3,support:50,bankBalance:0,loan:0,gdp:0,lastSystemOrder:[],
    voxels:[],districts:[],citizens:[],vehicles:[],shops:[],relationships:[],crimes:[],events:[],
    player:{position:{x:0,y:0,z:0},role:'traveler',money:100,reputation:0,needs:{hunger:80,fatigue:80,social:80,fun:80},inventory:{},homeId:null,education:0,experience:0,partnerId:null,vehicleId:null},
    metrics:{trades:0,commutes:0,crimesResolved:0,freight:0,flights:0},roadworks:{version:1,activatedAt:T,nextId:jobs.length+1,jobs,stock:[],capacityHistory:[]}};
}
function research(s: SimState, startedAt: number, workedMinutes: number, actorId = 'worker'): void {
  // Only the collector's read dependency is supplied. This is not an imported
  // schema-valid full extension or a controlled injection into Simulation.
  Reflect.set(s,'extension',{lastUpdate:NOW,runtime:{researchJobs:{traffic:{laborVersion:1,actorId,startedAt,workedMinutes}}}});
}
test('road capacity retains each actual-shaped paid interval without counting its aggregate twice',()=>{
  const s=state([job('one',[[T,T+4],[T+28,T+32]])]),before=JSON.stringify(s),claims=collectActorActivityClaims(s);
  assert.deepEqual(claims.map(c=>[c.startedAt,c.endedAt,c.workedMinutes]),[[T,T+4,4],[T+28,T+32,4]]);
  assert.equal(new Set(claims.map(c=>c.id)).size,2);assert.equal(claims.reduce((sum,c)=>sum+c.workedMinutes,0),8);
  assert.equal(JSON.stringify(s),before);assert.doesNotThrow(()=>validateJointActorActivityCapacity(s));
});
test('a late paid road segment cannot hide behind an early contribution start to overlap research',()=>{
  const s=state([job('gap',[[T,T+4],[T+28,T+32]])]);research(s,T+8,24);
  const before=JSON.stringify(s);assert.throws(()=>validateJointActorActivityCapacity(s),/容量/);assert.equal(JSON.stringify(s),before);
});
test('research which fits wholly in a real road-work gap remains a possible allocation',()=>{
  const s=state([job('gap',[[T,T+4],[T+28,T+32]])]);research(s,T+4,24);
  const before=JSON.stringify(s);assert.doesNotThrow(()=>validateJointActorActivityCapacity(s));assert.equal(JSON.stringify(s),before);
});
test('a coalesced continuous receipt stays one interval and claim IDs stay unique across jobs',()=>{
  const first=job('one',[[T,T+16]]);first.laborReceipts[0].lastTick=4;first.laborReceipts[0].paymentCount=4;
  const s=state([first,job('two',[[T+16,T+20]])]),claims=collectActorActivityClaims(s);
  assert.equal(claims.length,2);assert.equal(new Set(claims.map(c=>c.id)).size,2);assert.equal(claims[0].workedMinutes,16);
  assert.doesNotThrow(()=>validateJointActorActivityCapacity(s));
  s.roadworks!.jobs[1]=job('two',[[T+12,T+16]]);assert.throws(()=>validateJointActorActivityCapacity(s),/容量/);
});
test('different actors can occupy the same time window without consuming each other capacity',()=>{
  const s=state([job('one',[[T,T+4],[T+28,T+32]])]);research(s,T+8,24,'another-worker');
  assert.doesNotThrow(()=>validateJointActorActivityCapacity(s));
});
test('waiting road jobs and a cold state contribute no invented labor claims',()=>{
  const s=state([job('waiting',[])]);assert.deepEqual(collectActorActivityClaims(s),[]);assert.doesNotThrow(()=>validateJointActorActivityCapacity(s));
  delete s.roadworks;const before=JSON.stringify(s);assert.deepEqual(collectActorActivityClaims(s),[]);assert.equal(JSON.stringify(s),before);
});
test('future paid intervals and minutes exceeding their own continuous span still reject',()=>{
  const future=state([job('future',[[T+28,NOW+1]])]);assert.throws(()=>validateJointActorActivityCapacity(future),/分钟无效/);
  const excessive=state([job('excessive',[[T,T+4]])]);excessive.roadworks!.jobs[0].laborReceipts[0].minutes=5;
  assert.throws(()=>validateJointActorActivityCapacity(excessive),/分钟无效/);
});
