import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { Simulation } from '../src/simulation';
import { foodCounterWorld } from '../tests/helpers/food-counter-world';
const out='/tmp/yunshan-food-counter-archive-boundary-20261002';mkdirSync(out,{recursive:true});
const world=foodCounterWorld(),rt=(s:Simulation):any=>Reflect.get(s,'runtime');
function imported(){const s=new Simulation(world),r=s.importSave(readFileSync('/tmp/yunshan-food-counter-lifecycle-supported-v1-20261002/returned-save.json','utf8'));assert.equal(r.ok,true,r.message);assert.equal(s.command({type:'speed',value:1}).ok,true);return s;}
function settle(s:Simulation){const epoch=s.state.foodDistribution!.payroll.epoch;assert.equal(s.command({type:'setTime',value:16.99}).ok,true);for(let i=0;i<8&&s.state.foodDistribution!.payroll.epoch===epoch;i++)s.step(.25);assert.equal(s.state.foodDistribution!.payroll.epoch,epoch+1);}
function debt(s:Simulation){return [...(rt(s).wageArrears??[]),...rt(s).wages].filter(w=>w.shopId===null).reduce((n,w)=>n+w.amount,0);}
function outstanding(s:Simulation){const p=s.state.foodDistribution!.payroll;return Object.values(p.legacyDue).reduce((n,w)=>n+w,0)+p.periods.reduce((n,period)=>n+period.claims.reduce((n,c)=>n+c.amount-c.paidGross,0),0);}
test('forged paid receipt cannot conceal actual queued public debt before archival',()=>{
 const s=imported();settle(s);const saved=s.exportSave(),forged=JSON.parse(saved),period=forged.state.foodDistribution.payroll.periods[0],claim=period.claims.find(c=>c.amount>0);assert.ok(claim);const before=debt(s);assert.ok(before>0);const ledger=JSON.stringify(s.state.foodDistribution!.payroll);s.emitEvent({type:'wage-paid',citizenId:claim.citizenId,amount:claim.amount});assert.equal(JSON.stringify(s.state.foodDistribution!.payroll),ledger,'public event is not a genuine payroll payment');
 claim.paidGross=claim.amount;const receiver=new Simulation(world),beforeTarget=receiver.exportSave(),result=receiver.importSave(JSON.stringify(forged));writeFileSync(`${out}/real-unpaid-save.json`,saved);writeFileSync(`${out}/forged-paid-save.json`,JSON.stringify(forged));writeFileSync(`${out}/forged-paid-proof.json`,JSON.stringify({scope:'actual 17:00 original payroll; no amount injection; mutation only adversarial input paidGross; scheduler clock acceleration explicitly separate from natural-day rescue',actualQueuedDebt:before,observedLedgerOutstanding:outstanding(s),claim,importResult:result,rejectedAtomically:receiver.exportSave()===beforeTarget,oldDebtUnchanged:debt(s)===before},null,2)+'\n');assert.equal(result.ok,false,'unpaid actual wages must reject a forged paidGross before eligible-for-archive classification');assert.equal(receiver.exportSave(),beforeTarget);
});
test('257th genuine scheduler settlement must preserve prior debt and not halt already earned wage closure',()=>{
 const s=imported(),start=s.state.extension!.lastUpdate,progress:any[]=[];for(let i=0;i<256;i++){settle(s);if([0,1,63,127,254,255].includes(i))progress.push({epoch:s.state.foodDistribution!.payroll.epoch,time:s.state.extension!.lastUpdate,periods:s.state.foodDistribution!.payroll.periods.length,actualQueuedDebt:debt(s),ledgerOutstanding:outstanding(s),queuedRows:rt(s).wages.length});}
 const before={debt:debt(s),periods:JSON.stringify(s.state.foodDistribution!.payroll.periods),tasks:JSON.stringify(s.state.foodDistribution!.counters[0].tasks),wages:JSON.stringify(rt(s).wages)},save=s.exportSave();writeFileSync(`${out}/256-period-save.json`,save);const clone=new Simulation(world),load=clone.importSave(save);let thrown:string|null=null;try{settle(s)}catch(e){thrown=e instanceof Error?e.message:String(e)};
 writeFileSync(`${out}/257-period-proof.json`,JSON.stringify({scope:'256 actual original payroll callbacks from lawful setTime(16.99) plus real quarter-minute steps; NOT 256 natural days or city stability/performance; original actual queued debt kept',start,time:s.state.extension!.lastUpdate,progress,load256:load,exportExact256:load.ok&&clone.exportSave()===save,thrown,oldDebtRetained:debt(s)>=before.debt-1e-7,originalQueuedRowsUnchanged:JSON.stringify(rt(s).wages)===before.wages,periodsUnchanged:JSON.stringify(s.state.foodDistribution!.payroll.periods)===before.periods,finalEpoch:s.state.foodDistribution!.payroll.epoch,finalQueuedDebt:debt(s),finalAccruals:structuredClone(rt(s).wageAccruals)},null,2)+'\n');assert.ok(debt(s)>=before.debt-1e-7);assert.equal(JSON.stringify(rt(s).wages),before.wages,'already queued contractual debt remains');assert.equal(thrown,null,'history capacity must never interrupt closure of already earned labor');
});
