import assert from 'node:assert/strict';
import { readFileSync,writeFileSync } from 'node:fs';
import { Simulation } from '../src/simulation';
import { createWorld } from '../src/world';
const root='/tmp/yunshan-food-counter-normal-v1-natural-20261002',world=createWorld();
function inspect(path:string){const sim=new Simulation(world),loaded=sim.importSave(readFileSync(path,'utf8'));assert.equal(loaded.ok,true,loaded.message);const before=sim.exportSave(),s=sim.state,r:any=Reflect.get(sim,'runtime'),counter=s.foodDistribution!.counters[0],corporate=new Set(s.extension!.companies.map(c=>c.buildingId));
 const cash=s.treasury+r.taxes+s.player.money+s.citizens.reduce((n,c)=>n+c.money,0)+s.shops.filter(x=>!corporate.has(x.buildingId)).reduce((n,x)=>n+(x.cash??0),0)+s.extension!.companies.reduce((n,c)=>n+c.capital,0)+s.extension!.organizations.reduce((n,o)=>n+o.funds,0)+(s.banking?.cash??0)+(s.banking?.legacyInvestmentCash??0)+(s.playerLabor?.job?.escrow??0)+(s.family?.pregnancies.reduce((n,p)=>n+p.escrow,0)??0)+(s.family?.households.reduce((n,h)=>n+h.balance,0)??0)+(s.clinical?.orders.reduce((n,o)=>n+o.escrow,0)??0);
 const actors=[...new Set([counter.tasks[0].citizenId,...counter.approvedBy])].map(id=>{const p=s.citizens.find(c=>c.id===id)!,target=p.destinationId&&world.buildings.find(b=>b.id===p.destinationId);return{id,homeId:p.homeId,workId:p.workId,role:p.role,hunger:p.needs.hunger,food:p.food,money:p.money,destination:p.destinationId,targetCommodity:target&&s.shops.find(x=>x.buildingId===target.id)?sim.shopCommodity(s.shops.find(x=>x.buildingId===target.id)!):null,homeToChosenTargetRoadDistance:target?sim.buildingTravelDistance(p.homeId,target.id):null,homeToJobRoadDistance:sim.buildingTravelDistance(p.homeId,p.workId),onDuty:sim.isOnDuty(id,p.workId)}});
 const sourceIds=new Set(counter.stocks.map(s=>s.sourceLotId)),lots=(Object.values(r.freightLots??{}).flat() as any[]).filter(x=>sourceIds.has(x.id)),sourceBalances=counter.stocks.map(stock=>({sourceLotId:stock.sourceLotId,nodeId:stock.origin.nodeId,owner:stock.origin.shopId,originalReceived:stock.origin.receivedQuantity,currentOriginalFreight:lots.filter(l=>l.id===stock.sourceLotId).reduce((n,l)=>n+l.quantity,0),held:counter.stocks.filter(s=>s.sourceLotId===stock.sourceLotId).reduce((n,s)=>n+s.remaining,0),sold:counter.stocks.filter(s=>s.sourceLotId===stock.sourceLotId).reduce((n,s)=>n+s.sold,0),returned:counter.stocks.filter(s=>s.sourceLotId===stock.sourceLotId).reduce((n,s)=>n+s.returned,0)}));
 const result={time:s.extension!.lastUpdate,hour:s.hour,physicalCash:cash,actors,localFoodRetailers:s.shops.filter(x=>x.districtId===counter.districtId&&sim.shopCommodity(x)==='food').map(x=>({id:x.id,inventory:x.inventory})),counter:{siteId:counter.siteId,state:counter.state,stockRemaining:counter.stocks.reduce((n,s)=>n+s.remaining,0),sales:counter.sales.length,materialReceived:counter.materialReceived,materialConsumed:counter.materialConsumed,assemblyMinutes:counter.assemblyMinutes,spent:counter.spent},sourceBalances,publicArrears:((r.wageArrears??[]) as {shopId:string|null;amount:number}[]).filter(x=>x.shopId===null).reduce((n,x)=>n+x.amount,0),privateArrears:((r.wageArrears??[]) as {shopId:string|null;amount:number}[]).filter(x=>x.shopId!==null).reduce((n,x)=>n+x.amount,0),readonlyQueriesPreservedSave:before===sim.exportSave()};assert.ok(result.readonlyQueriesPreservedSave);return result;
}
const initial=inspect('/tmp/yunshan-food-counter-normal-v1-capture-20261002/paid-normal-v1-save.json'),final=inspect(`${root}/natural-plus24-save.json`);writeFileSync(`${root}/readonly-analysis.json`,JSON.stringify({scope:'read-only authoritative geometry and real custody/physical cash, no additional simulation ticks; whole-city production/consumption event window was not subscribed so food global flow residual NOT_CALCULATED',initial,final,cashResidual:final.physicalCash-initial.physicalCash},null,2)+'\n');
