import { createHash } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { useWorldSnapshots, type WorldSnapshot } from '../persistence/world-cache';

/** Packaged world snapshots (scripts/build-sim-host.mjs) are generated by the
 * very bundle they sit beside: the file names that bundle's SHA-256 and is
 * used only when the running bundle has the same bytes. Any mismatch, a
 * missing file or a malformed entry leaves world generation as it was. */
export interface WorldSnapshotFile { format: 'yunshan-world-snapshots'; version: 1; bundleSha256: string; seed: number; snapshots: Record<string, WorldSnapshot> }

export function installPackagedWorldSnapshots(bundlePath: string, snapshotPath: string): boolean {
  if (!existsSync(bundlePath) || !existsSync(snapshotPath)) return false;
  try {
    const file = JSON.parse(gunzipSync(readFileSync(snapshotPath)).toString('utf8')) as WorldSnapshotFile;
    const sha = createHash('sha256').update(readFileSync(bundlePath)).digest('hex');
    if (file.format !== 'yunshan-world-snapshots' || file.version !== 1 || file.bundleSha256 !== sha || !Number.isSafeInteger(file.seed)) return false;
    for (const snapshot of Object.values(file.snapshots)) if (typeof snapshot?.text !== 'string' || !Array.isArray(snapshot.aliases) || typeof snapshot.fingerprint !== 'string') return false;
    useWorldSnapshots((seed, layout) => seed === file.seed ? file.snapshots[layout] ?? null : null);
    return true;
  } catch { return false; }
}
