import assert from 'node:assert/strict';
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { PerspectiveCamera } from 'three';
import { planWalkingJourney, planTransitJourney } from './src/journey.ts';
import { marketCounters } from './src/site-fixtures.ts';
import { getWalkHeight } from './src/world.ts';
import { PlayerController } from './src/controller.ts';
import type { SimState, WorldDefinition } from './src/types.ts';
const sha=(bytes:Uint8Array)=>createHash('sha256').update(bytes).digest('hex');
const manifest=JSON.parse(readFileSync('source-manifest.json','utf8'));
const check=()=>assert.deepEqual(Object.fromEntries(Object.keys(manifest.sourceHashes).map(path=>[path,sha(readFileSync(path))])),manifest.sourceHashes);
check();const baseline=JSON.parse(readFileSync('counter-baseline-input.json','utf8')),world:WorldDefinition=baseline.world;
const counter=marketCounters(world,world.buildings[0])[0];assert.deepEqual(counter,baseline.counter);
const from={...baseline.actualFrom};assert.equal(from.y,getWalkHeight(world,from.x,from.z,world.buildings[0].door.y));
const player={position:from,inventory:{},money:100,role:'traveler',identities:['traveler']},state={day:0,hour:8,energy:100,visibility:1,player,vehicles:[]}as unknown as SimState;
const before=JSON.stringify({world,state,from}),walking=planWalkingJourney(world,from,'B'),transit=planTransitJourney(world,state,from,'B');assert.equal(walking,null);assert.equal(transit,null);assert.equal(JSON.stringify({world,state,from}),before);
const keyboard=Object.assign(new EventTarget(),{closest:()=>null}),doc=Object.assign(new EventTarget(),{pointerLockElement:null});Object.defineProperty(globalThis,'window',{value:keyboard,configurable:true});Object.defineProperty(globalThis,'document',{value:doc,configurable:true});
const controller=new PlayerController(new PerspectiveCamera(),new EventTarget()as HTMLCanvasElement,world,()=>{},()=>true,()=>[]);controller.setMode('walk',from);
const target=baseline.oldRoute.points[1],event=new Event('keydown');Object.assign(event,{code:'KeyW',repeat:false});keyboard.dispatchEvent(event);controller.yaw=Math.atan2(from.x-target.x,from.z-target.z);for(let i=0;i<100;i++)controller.step(.1,false);
const actualFinal=controller.position;controller.dispose();assert.deepEqual(actualFinal,baseline.actualController.actualFinal);check();
const result={status:'PASS',scope:'Same actual provider/controller cabinet-side fixture as immutable03 failure. Shared guard now rejects both planners explicitly; no claimed terrain detour.',sourceCount:89,sourceHashesStable:true,counter,actualFrom:from,walking,transit,unchangedWorldAndPlayer:true,actualController:{key:'KeyW',steps:100,dt:.1,actualFinal,unreachedProjection:target},oldPlannerHadCrossing:true};writeFileSync('counter-check-results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
