import assert from 'node:assert/strict';import{readFileSync,writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{gunzipSync}from'node:zlib';import{PerspectiveCamera}from'three';
import{PlayerController}from'./src/controller.ts';import{selectSavedWorld}from'./src/persistence/world-layout.ts';import{planWalkingJourney,planTransitJourney}from'./src/journey.ts';import{getWalkHeight,terrainHeight}from'./src/world.ts';import{canAccessFloor}from'./src/access.ts';
const sha=(data:string|Uint8Array)=>createHash('sha256').update(data).digest('hex');
const manifest=JSON.parse(readFileSync('./source-manifest.json','utf8'));const sourceHashes=()=>Object.fromEntries(Object.keys(manifest.sourceHashes).map(path=>[path,sha(readFileSync(path))]));assert.deepEqual(sourceHashes(),manifest.sourceHashes);
const raw=gunzipSync(readFileSync('./tests/fixtures/journey/r7-native-ui-export-coherent02.json.gz'));assert.equal(sha(raw),manifest.nativeSHA256);const json=raw.toString('utf8'),data=JSON.parse(json),{world,layout}=selectSavedWorld(json),from=data.state.player.position;
const walking=planWalkingJourney(world,from,'academy-b13')!,transit=planTransitJourney(world,data.state,from,'academy-b13')!;assert(walking);assert(transit);
const endpoint=world.nodes.find(node=>node.id===walking.originNodeId)!;const endIndex=walking.points.findIndex(p=>Math.hypot(p.x-endpoint.position.x,p.y-endpoint.position.y,p.z-endpoint.position.z)<.01);
assert.equal(walking.points[1].z,512);assert.equal(walking.edgeIds[0],'road-market-quarter-1-market-station');
const keyboard=Object.assign(new EventTarget(),{closest:()=>null}),doc=Object.assign(new EventTarget(),{pointerLockElement:null});Object.defineProperty(globalThis,'window',{value:keyboard,configurable:true});Object.defineProperty(globalThis,'document',{value:doc,configurable:true});
const controller=new PlayerController(new PerspectiveCamera(),new EventTarget()as HTMLCanvasElement,world,()=>{},(building,floor)=>canAccessFloor(building,floor,data.state.player),()=>data.state.voxels);controller.setMode('walk',from);
const event=new Event('keydown');Object.assign(event,{code:'KeyW',repeat:false});keyboard.dispatchEvent(event);const history=[];let inputs=0;
for(const target of walking.points.slice(1,endIndex+1)){
  const before=controller.position;let reached=false;
  for(let step=0;step<1000;step++){
    const body=controller.position,dx=target.x-body.x,dz=target.z-body.z,distance=Math.hypot(dx,dz);if(distance<.03){reached=true;break;}
    controller.yaw=Math.atan2(-dx,-dz);controller.step(Math.min(.1,distance/4.8),false);inputs++;
  }
  assert(reached,JSON.stringify({target,actual:controller.position}));history.push({target,before,after:controller.position,actualWalkHeight:getWalkHeight(world,controller.position.x,controller.position.z,controller.position.y),ground:terrainHeight(world,controller.position.x,controller.position.z),inside:controller.inside?.id??null,floor:controller.floor});
}
const final=controller.position;controller.dispose();assert(Math.hypot(final.x-endpoint.position.x,final.z-endpoint.position.z)<.03);assert.equal(data.state.paused,true);assert.equal(JSON.stringify(data),json);assert.deepEqual(sourceHashes(),manifest.sourceHashes);
const result={scope:'New journey+counter guard on immutable coherent03 base, actual r7 native body, real unchanged PlayerController KeyW through first actual road polyline to endpoint. CPU authority proof, not a completed browser school journey.',sourceSnapshot:'/tmp/yunshan-journey-prefix-after-02',sourceCount:89,sourceHashesStable:true,nativeSHA256:sha(raw),nativeBytes:raw.length,recipe:layout,actualFrom:from,actualPlayerMoney:data.state.player.money,actualClock:{tick:data.state.tick,day:data.state.day,hour:data.state.hour,paused:data.state.paused},walking,transit:{originNodeId:transit.approach.originNodeId,approach:transit.approach,legs:transit.legs,fare:transit.fare,walkingMetres:transit.walkingMetres,transfers:transit.transfers},prefixReached:{endpointId:endpoint.id,endpoint:endpoint.position,actualFinal:final,controllerStepCount:inputs,waypoints:history},unchangedPlayerSave:true,limits:['Only the first road access and its endpoint were physically walked in the CPU controller fixture.','The remainder of the school route and normal keyboard/mouse browser journey require the next coherent-build GL check.','Planner connector checks static world road/bridge layers, buildings, river and shared counter/transport barriers; player-built voxel changes are not supplied to this API.','Off-road joining tests a direct short connector; it does not run a free-terrain obstacle-detour pathfinder.']};writeFileSync('journey-proof-results.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:'PASS',sourceHashesStable:true,nativeSHA256:sha(raw),projection:walking.points[1],firstEdge:walking.edgeIds[0],endpointId:endpoint.id,actualFinal:final,controllerStepCount:inputs,transitApproachPrefixPreserved:true},null,2));
