import type { GovernanceState } from './simulation/governance';
import type { FamilyState } from './simulation/family';
import type { CultureState } from './simulation/culture';
import type { ClinicalState } from './simulation/clinical';
import type { EducationState } from './simulation/education';
import type { FamilyEducationState } from './simulation/family-education';
import type { BankingState } from './simulation/banking';
import type { TransitJourney, WalkingJourney } from './journey';
import type { JourneyState } from './simulation/journeys';
import type { TradeState } from './simulation/trade';
import type { PlayerLaborState } from './simulation/player-labor';
import type { HomeRestState } from './simulation/home-rest';
import type { PowerState } from './simulation/power';
import type { ShopLifecycleState } from './simulation/shop_lifecycle';
import type { HygieneState } from './simulation/hygiene';
import type { PathologyState } from './simulation/pathology';
import type { RoadNetworkState } from './roads';
import type { RoadworksState } from './simulation/roadworks';
import type { RoadDemandsState } from './simulation/road-demands';
import type { CivicStaffingState } from './simulation/civic-staffing';
import type { CivicHistoryState } from './simulation/civic-history';
import type { BudgetAuthorityState } from './simulation/budget-authority';
export interface Vec3 { x: number; y: number; z: number }
export type ViewMode = 'drone' | 'walk' | 'jet';
export type Quality = 'low' | 'balanced' | 'high';
export type Role = 'traveler' | 'police' | 'soldier' | 'teacher' | 'driver' | 'merchant' | 'mayor' | 'scientist' | 'official' | 'council';
export type BuildingKind = 'home' | 'market' | 'workshop' | 'bank' | 'hall' | 'police' | 'school' | 'clinic' | 'station' | 'core' | 'pavilion' | 'airport' | 'starport' | 'farm' | 'dock';
export type TransportMode = 'road' | 'maglev' | 'lightRail' | 'cable' | 'lift' | 'ferry' | 'bridge' | 'flight';
export interface District { id: string; name: string; kind: string; center: Vec3; radius: number; color: string; population: number }
/** Authoritative occupied floor points, derived by the trusted building recipe. */
export interface BuildingFunctionPoint { id: string; purpose: 'work' | 'service' | 'sale'; floor: number; position: Vec3 }
export interface Building { commercialRouteRevision?: 1; commercialGeometryRevision?: 1; stairGeometryRevision?: 2; floorPlanProfile?: 'v4-program-bodies-02'; functionPoints?: BuildingFunctionPoint[]; floorFootprints?: { width: number; depth: number }[]; basements?: number; basementUses?: string[]; floorUses?: string[]; floorPermissions?: string[]; facility?: 'mayor' | 'council' | 'administration' | 'data' | 'energy' | 'emergency' | 'embassy' | 'archives' | 'treasury'; publicFloors?: number; requiredPermission?: string; id: string; districtId: string; name: string; kind: BuildingKind; position: Vec3; width: number; depth: number; height: number; floors: number; rotation: number; door: Vec3; capacity: number; seed: number }
export interface NetworkNode { id: string; districtId: string; name: string; position: Vec3; station: boolean }
export interface NetworkEdge { id: string; from: string; to: string; mode: TransportMode; length: number; capacity: number; points: Vec3[] }
export interface Mountain { x: number; z: number; height: number; radius: number }
export interface WorldDefinition { seed: number; voxelSize: number; size: number; districts: District[]; buildings: Building[]; nodes: NetworkNode[]; edges: NetworkEdge[]; mountains: Mountain[]; spawn: Vec3; waterfall: { top: Vec3; bottom: Vec3; width: number }; river: Vec3[] }
export interface Needs { hunger: number; fatigue: number; social: number; fun: number }
export interface Citizen { food?: number; skills?: Record<string, number>; socialIdentities?: string[]; historyTags?: string[]; education?: number; id: string; name: string; districtId: string; homeId: string; workId: string; role: string; position: Vec3; state: string; destinationId: string | null; money: number; needs: Needs; tier: 'active' | 'regional' | 'statistical'; route?: Vec3[]; routeIndex?: number; partnerId?: string | null }
export interface Vehicle { id: string; kind: TransportMode; position: Vec3; edgeId: string; progress: number; direction: number; speed: number; state: string; passengers: number; cargo: number; nextDeparture: number }
export interface Shop { lifecycleVersion?: 1; cash?: number; ownerId?: string; id: string; buildingId: string; districtId: string; inventory: number; price: number; revenue: number; profit: number; customers: number; open: boolean; employees: number }
export interface DistrictState { id: string; energy: number; safety: number; employment: number; prosperity: number; pollution: number; tier: 'active' | 'regional' | 'statistical'; residents: number; crimeCount: number }
export interface Relationship { romanceStage?: 'single' | 'crush' | 'pursuit' | 'dating' | 'engaged' | 'married' | 'family'; hostilityStage?: 'none' | 'discontent' | 'rivalry' | 'feud' | 'enemy' | 'mortalEnemy'; romanceSince?: number; hostilitySince?: number; conflicts?: number; reconciliations?: number; consent?: boolean; npcId: string; affection: number; trust: number; type: string; encounters: number; memories: { tick: number; text: string; impact: number }[]; tags: string[] }
export interface Player { identities?: Role[]; position: Vec3; role: Role; money: number; reputation: number; needs: Needs; inventory: Record<string, number>; homeId: string | null; education: number; experience: number; partnerId: string | null; vehicleId: string | null }
export interface CityEvent { id: number; tick: number; type: string; text: string; districtId?: string }
export interface Crime { id: string; districtId: string; position: Vec3; severity: number; status: 'open' | 'responding' | 'resolved'; responseAt: number }
export interface VoxelModification { id: string; position: Vec3; color: string }
export interface SimState { civicHistory?: CivicHistoryState; budgetAuthority?: BudgetAuthorityState; civicStaffing?: CivicStaffingState; familyEducation?: FamilyEducationState; roadDemands?: RoadDemandsState; roadNetwork?: RoadNetworkState; roadworks?: RoadworksState; hygiene?: HygieneState; pathology?: PathologyState; governance?: GovernanceState; shopLifecycle?: ShopLifecycleState; power?: PowerState; education?: EducationState; homeRest?: HomeRestState; clinical?: ClinicalState; playerLabor?: PlayerLaborState; trade?: TradeState; journey?: JourneyState; banking?: BankingState; culture?: CultureState; family?: FamilyState; aviation?: AviationState; extension?: CityExtensionState; signals?: Record<string, 0 | 1>; voxels: VoxelModification[]; version: number; seed: number; tick: number; day: number; hour: number; paused: boolean; speed: number; weather: string; visibility: number; energy: number; treasury: number; taxRate: number; policeBudget: number; support: number; bankBalance: number; loan: number; gdp: number; lastSystemOrder: string[]; districts: DistrictState[]; citizens: Citizen[]; vehicles: Vehicle[]; shops: Shop[]; player: Player; relationships: Relationship[]; crimes: Crime[]; events: CityEvent[]; policyPending?: { taxRate: number; policeBudget: number; applyAt: number }; metrics: { trades: number; commutes: number; crimesResolved: number; freight: number; flights: number } }
export interface Command { type: 'transferWaste' | 'collectWasteTransfer' | 'deliverWasteTransfer' | 'cancelWasteTransfer' | 'enrollFamilyCourse' | 'cancelFamilyCourse' | 'resumeFamilyCourse' | 'requestRoadRepair' | 'approveRoadRepair' | 'cancelRoadRepair' | 'disinfectWaste' | 'cancelDisinfection' | 'suspendShop' | 'listShopForSale' | 'listShopForLease' | 'withdrawShopListing' | 'buyShop' | 'leaseShop' | 'fundShop' | 'restartShop' | 'endShopLease' | 'payShopRent' | 'cancelEnergy' | 'requestEnergyRepair' | 'approveEnergyRepair' | 'cancelStudy' | 'cancelRest' | 'fileUtilityProposal' | 'reviewUtilityProposal' | 'payUtilityBill' | 'fundUtilityRelief' | 'cancelTreatment' | 'cancelWork' | 'planJourney' | 'cancelJourney' | 'buyEstateAsset' | 'moveHousehold' | 'fundHousehold' | 'householdMeal' | 'holdCeremony' | 'redeemLegacyInvestment' | 'reviewPetition' | 'attendService' | 'createWork' | 'publishWork' | 'publishReport' | 'verifyReport' | 'correctReport' | 'filePetition' | 'planFamily' | 'supportFamily' | 'enrollChild' | 'rentAircraft' | 'boardAircraft' | 'leaveAircraft' | 'landAircraft' | 'returnAircraft' | 'refuelAircraft' | 'foundCompany' | 'expandCompany' | 'listCompany' | 'buyShares' | 'sellShares' | 'acquireCompany' | 'hire' | 'research' | 'cook' | 'buyIngredient' | 'eat' | 'audit' | 'reportCorruption' | 'investigate' | 'heal' | 'joinOrganization' | 'donate' | 'attendFestival' | 'appoint' | 'setTime' | 'pause' | 'speed' | 'purchase' | 'work' | 'rest' | 'socialize' | 'gift' | 'court' | 'propose' | 'divorce' | 'conflict' | 'reconcile' | 'exam' | 'election' | 'policy' | 'resolveCrime' | 'rent' | 'deposit' | 'withdraw' | 'loan' | 'repay' | 'invest' | 'business' | 'ride' | 'leaveVehicle' | 'drive' | 'build' | 'demolish' | 'signal' | 'energy'; utilityBusinessRate?: number; title?: string; text?: string; targetId?: string; value?: number; taxRate?: number; policeBudget?: number; position?: Vec3 }
export interface CommandResult { ok: boolean; message: string }
export interface SimulationAPI { state: SimState; step(realSeconds: number): void; command(command: Command): CommandResult; setFocus(position: Vec3, mode: ViewMode): void; exportSave(): string; importSave(json: string): CommandResult }
export interface ViewState { navigationUnavailable?: string | null; transitJourney?: TransitJourney | null; journey?: WalkingJourney | null; nearbyAircraft?: AerialVehicle | null; mode: ViewMode; quality: Quality; fps: number; drawCalls: number; triangles: number; position: Vec3; nearbyBuilding: Building | null; nearbyCitizen: Citizen | null; nearbyVehicle: Vehicle | null; targetDistrict: string | null; inside: boolean; notice?: string; renderDistance: number; fpsCap: number; dynamicResolution: boolean; simulationDetail: number }
export interface UIActions { publicEmploymentStatus?(): { rule:string;reason:string;standingActive:boolean;actors:{name:string;siteName:string;fundedMinutes:number;actualMinutes:number;remainingMinutes:number}[] } | null; isAtBuildingFunctionPoint?(buildingId: string, purpose?: BuildingFunctionPoint['purpose']): boolean; navigateTarget?(targetId: string, preference?: 'walk' | 'transit'): void; navigateAircraft?(aircraftId: string): void; command(command: Command): void; setMode(mode: ViewMode): void; setQuality(quality: Quality): void; travel(targetId: string, preference?: 'walk' | 'transit'): void; interact(): void; save(): void; load(): void; exportSave(): void; importSave(file: File): void; setSetting(key: string, value: number | boolean): void; resetView(): void }
export interface CityRendererAPI { update(state: SimState, elapsed: number): void; render(): void; resize(): void; setQuality(quality: Quality): void; setRenderDistance(distance: number): void; setDynamicResolution(enabled: boolean): void; camera: import('three').PerspectiveCamera; scene: import('three').Scene; renderer: import('three').WebGLRenderer; dispose(): void }

export interface Company { shopBindingId?: string; shopBindingReleasedAt?: number; id: string; name: string; ownerId: string; buildingId: string; districtId: string; capital: number; shares: number; sharePrice: number; listed: boolean; employees: number; inventory: number; revenue: number; profit: number; level: number; marketShare: number; shareholders: Record<string, number>; foundedAt: number; parentId: string | null }
export interface Technology { sector: 'traffic' | 'energy' | 'information' | 'security' | 'medicine' | 'agriculture' | 'manufacturing'; level: number; progress: number; funding: number; sideEffect: number }
export interface AuditCase { id: string; npcId: string; evidence: number; diverted: number; status: 'suspected' | 'reported' | 'investigating' | 'prosecuted' | 'cleared'; createdAt: number; responseAt: number }
export interface LifeProfile { age: number; health: number; mood: number; stress: number; alive: boolean; skill: number; family: string[]; historyTags: string[] }
export interface LedgerEntry { sourceEvent?: 'transit-fare' | 'public-payroll-escrow' | 'utility-payment'; tick: number; actorId: string; amount: number; purpose: string; account: 'public' | 'company' | 'household'; districtId: string }
/** Unmarked pending jobs retain their historical deadline contract on load. */
export interface LegacyResearchJob { startedAt: number; finishAt: number; budget: number; actorId?: string; laborVersion?: undefined }
/** finishAt is the earliest deadline; actual attended work is authoritative. */
export interface AttendedResearchJob { startedAt: number; finishAt: number; budget: number; actorId: string; laborVersion: 1; siteId: string; floor: number; workedMinutes: number; lastObservedAt: number; state: 'active' | 'paused'; pauseReason: string }
export type ResearchJob = LegacyResearchJob | AttendedResearchJob;
export interface CookingJob { recipeId: string; startedAt: number; finishAt: number; quality: number }
export interface Organization { id: string; name: string; kind: string; members: string[]; reputation: number; funds: number }
export interface CityExtensionState { version: number; companies: Company[]; technologies: Technology[]; audits: AuditCase[]; actorProfiles: Record<string, LifeProfile>; publicLedger: LedgerEntry[]; cooking: CookingJob | null; organizations: Organization[]; environment: { waterQuality: number; biodiversity: number; stormRisk: number; disasterAt: number; lastDisaster: string }; institutions: { education: number; medical: number; welfare: number; culture: number }; lastUpdate: number; nextCompanyId: number; nextAuditId: number; stats: { mealsCooked: number; researchCompleted: number; corruptionRecovered: number; donations: number; festivals: number } }

/** Aircraft are city entities, separate from vehicles constrained to network edges. */
export interface AviationPad { id: string; name: string; districtId: string; position: Vec3; kind: 'rental' | 'military' }
export interface AerialVehicle { id: string; name: string; kind: 'drone' | 'jet'; homePadId: string; padId: string | null; position: Vec3; yaw: number; pitch: number; speed: number; battery: number; status: 'parked' | 'flying' | 'landing'; reserved: boolean; charging: boolean; landingPadId: string | null }
export interface AviationControls { forward: number; strafe: number; climb: number; yaw: number; pitch: number; speed: number; boost: boolean }
export interface AviationState { version: 1; aircraft: AerialVehicle[]; activeAircraftId: string | null; controls: AviationControls; stats: { rentals: number; flights: number; landings: number; fees: number } }
