import {readFile,writeFile} from 'node:fs/promises';
import {createWorld} from '../src/world';import {Simulation} from '../src/simulation';
const world=createWorld(20261001),sim=new Simulation(world),save=await readFile('artifacts/food-material-final.save.json','utf8');const load=sim.importSave(save);if(!load.ok)throw new Error(load.message);const before=sim.exportSave();
const sites=new Map(world.buildings.map(b=>[b.id,b])),core=Reflect.get(sim,'runtime'),food=sim.state.shops.filter(s=>sim.shopCommodity(s)==='food');
const alive=sim.state.citizens.filter(c=>sim.state.extension!.actorProfiles[c.id].alive),rich=alive.filter(c=>c.needs.hunger<20&&c.money>=15);
const Eu=(a:any,b:any)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);const walk=(c:any,b:any)=>Reflect.get(sim,'walkingDistance').call(sim,c,b)as number;
const rows=[];const counts={poorWalletForEveryInStockFood:0,noStockInOwnDistrict:0,noOpenStockInOwnDistrict:0,noRouteToAnyAffordableOpenFood:0,blockedOnlyBy1200CrossDistrict:0,nearestActualAffordableOpenFoodOver500:0,nearestActualAffordableOpenFoodOver1000:0,nearestActualAffordableOpenFoodOver2500:0,currentlyChoosingEat:0,otherActivityWithNoAdvertisedFood:0,advertisedFoodUnsellable:0};
for(const c of rich){const inStock=food.filter(s=>s.inventory>=1),open=inStock.filter(s=>s.open),aff=open.filter(s=>c.money>=s.price),unrestricted=aff.map(s=>({shopId:s.id,kind:sites.get(s.buildingId)!.kind,districtId:s.districtId,stock:s.inventory,price:s.price,straight:Eu(c.position,sites.get(s.buildingId)!.door),walk:walk(c,sites.get(s.buildingId)!)})).filter(r=>Number.isFinite(r.walk)).sort((a,b)=>a.walk-b.walk),advertised=unrestricted.filter(r=>r.straight<=1200||r.districtId===c.districtId),own=inStock.filter(s=>s.districtId===c.districtId),ownOpen=own.filter(s=>s.open);let unsellable=0;
for(const r of advertised){const shop=sim.state.shops.find(s=>s.id===r.shopId)!;const quantity=Math.min((c.food??0)<1?2:1,Math.floor(c.money/shop.price),Math.floor(shop.inventory));let reason='';try{const q=sim.quoteConsignmentSale(shop.id,quantity,shop.inventory);if(shop.price*quantity*(1-sim.state.taxRate)<q.supplierGross)reason='consigned price exceeds actual sale payment';if(sim.shopFunds(shop)+shop.price*quantity*(1-sim.state.taxRate)-q.supplierGross>1e9)reason='cash cap';}catch(err){reason=String(err);}if(reason)unsellable++;}
if(!inStock.some(s=>c.money>=s.price))counts.poorWalletForEveryInStockFood++;if(!own.length)counts.noStockInOwnDistrict++;if(!ownOpen.length)counts.noOpenStockInOwnDistrict++;if(!unrestricted.length)counts.noRouteToAnyAffordableOpenFood++;if(unrestricted.length&&!advertised.length)counts.blockedOnlyBy1200CrossDistrict++;if(unrestricted[0]?.walk>500)counts.nearestActualAffordableOpenFoodOver500++;if(unrestricted[0]?.walk>1000)counts.nearestActualAffordableOpenFoodOver1000++;if(unrestricted[0]?.walk>2500)counts.nearestActualAffordableOpenFoodOver2500++;if(core.activities[c.id]==='eat')counts.currentlyChoosingEat++;if(core.activities[c.id]!=='eat'&&!advertised.length)counts.otherActivityWithNoAdvertisedFood++;if(advertised.length&&unsellable===advertised.length)counts.advertisedFoodUnsellable++;
rows.push({id:c.id,districtId:c.districtId,role:c.role,wallet:c.money,hunger:c.needs.hunger,state:c.state,activity:core.activities[c.id],destinationId:c.destinationId,routeIndex:c.routeIndex,routeLength:c.route.length,ownInStock:own.length,ownOpenInStock:ownOpen.length,actualAffordableReachable:unrestricted.length,advertised:advertised.length,nearestActual:unrestricted.slice(0,2),nearestAdvertised:advertised.slice(0,2),unsellableAdvertised:unsellable});}
const districts=world.districts.map(d=>{const shops=food.filter(s=>s.districtId===d.id),buyers=rich.filter(c=>c.districtId===d.id),lots=core.freightLots?.[d.id]??[];return{id:d.id,name:d.name,richStarving:buyers.length,foodShops:shops.length,inStockShops:shops.filter(s=>s.inventory>=1).length,openInStockShops:shops.filter(s=>s.open&&s.inventory>=1).length,stock:shops.reduce((n,s)=>n+s.inventory,0),shopCash:shops.reduce((n,s)=>n+sim.shopFunds(s),0),protectedCash:shops.reduce((n,s)=>n+sim.shopProtectedFunds(s),0),freight:core.freight[d.id]??0,freightLots:lots.length,leadingFreight:lots[0]??null};});
const unchanged=sim.exportSave()===before;if(!unchanged)throw new Error('Read-only access analysis changed state');const data={at:sim.state.extension!.lastUpdate,day:sim.state.day,hour:sim.state.hour,richHungry:rich.length,counts,districts,rows,unchanged};await writeFile('artifacts/food-access-analysis.json',JSON.stringify(data,null,2));console.log(JSON.stringify({...data,rows:undefined}));
